/*
 *			sample_applications/Cakefile
 *
 *  $Header: /usr/Backup/upgrade/brlcad/brlcad/sample_applications/Cakefile,v 1.3 1999-05-14 15:15:20 bparker Exp $
 */
#include "../Cakefile.defs"

#define PRODUCTS	*.c *.h makefile
#define SRCDIR	sample_applications
#undef BINDIR
#define BINDIR	BASEDIR/sample_applications
#undef BINPERM
#define BINPERM 444
#define MANSECTION	1

#define BUILD_MAKEFILE ./build_makefile.sh

clean&:
	@echo "" > /dev/null

noprod&:
	rm -f makefile

clobber&:
	@echo "" > /dev/null

makefile:
	BUILD_MAKEFILE

#include "../Cakefile.rules"
