/*
 *			patch/Cakefile
 *
 *  $Header: /usr/Backup/upgrade/brlcad/brlcad/patch/Cakefile,v 1.2 1994-03-11 16:43:27 mike Exp $
 */
#define SRCDIR	patch
#define PRODUCTS	patch-g rpatch
#define	SRCSUFF	.c
#define MANSECTION	1

#include "../Cakefile.defs"
#include "../Cakefile.prog"

patch-g:	patch-g.o LIBRT
	CC LDFLAGS  patch-g.o LIB_PRE''LIBWDB LIB_PRE''LIBRT RT_CONFIG LIBRT_LIBES LIBES -o patch-g

rpatch:		../SRCDIR/rpatch.f
	FC FFLAGS ../SRCDIR/rpatch.f -o rpatch

#include "../Cakefile.rules"
