/*
 *			vas4/Cakefile
 *
 *  $Header: /usr/Backup/upgrade/brlcad/brlcad/vas4/Cakefile,v 10.1 1991-10-12 06:50:27 mike Exp $
 */

#define SRCDIR	vas4
#define PRODUCTS	vas4
#define	SRCSUFF	.c
#define MANSECTION	1

#define FILES	vas4 vas_io record_seq

#include "../Cakefile.defs"
#include "../Cakefile.prog"

/* Explicit composition of each product */

vas4:	OBJ LIBFB
	CC LDFLAGS -o vas4 OBJ LIB_PRE''LIBFB LIBFB_LIBES LIBES

#include "../Cakefile.rules"
