/*
 *			vas4/Cakefile
 *
 *  $Header: /usr/Backup/upgrade/brlcad/brlcad/vas4/Cakefile,v 11.1 1995-01-04 10:18:29 mike Exp $
 */

#define SRCDIR	vas4
#define PRODUCTS	vas4
#define	SRCSUFF	.c
#define MANSECTION	1

#define FILES	vas4 vas_io record_seq

#include "../Cakefile.defs"
#include "../Cakefile.prog"

/* Explicit composition of each product */

vas4:	OBJ
	CC LDFLAGS -o vas4 OBJ LIBFB LIBFB_LIBES LIBES

#include "../Cakefile.rules"
