/*
 *	$Header: /usr/Backup/upgrade/brlcad/brlcad/halftone/Cakefile,v 2.1 1990-04-13 03:09:40 cjohnson Exp $
 *
 *			halftone/Cakefile
 */

#define SRCDIR	halftone
#define PRODUCTS	halftone
#define	SRCSUFF	.c
#define MANSECTION	1

#define FILES	main msran sharpen tone_classic tone_floyd tone_folly \
		tone_simple tonescale

#include "../Cakefile.defs"
#include "../Cakefile.prog"

/* Explicit composition of each product */

halftone:	OBJ 
	CC LDFLAGS -o halftone OBJ LIBES

#include "../Cakefile.rules"
