/*
 *			libwdb/Cakefile
 *
 *  $Header: /usr/Backup/upgrade/brlcad/brlcad/libwdb/Cakefile,v 11.5 2000-02-02 21:14:31 jra Exp $
 */
#define PRODUCTS	libwdb.ARCH_SUF
#define SRCDIR	libwdb
#define FILES	wdb reg spl ars arbn units pipe export nmg poly id strsol fgp bot skt extr
#define	SRCSUFF	.c
#define MANSECTION	3

#define VERSION_VARIABLE	libwdb_version
#define LIBRARY_TITLE		"BRL-CAD Library for Writing Databases"

#include "../Cakefile.defs"

#include "../Cakefile.lib"
#include "../Cakefile.rules"
