/*
 *			libwdb/Cakefile
 *
 *  $Header: /usr/Backup/upgrade/brlcad/brlcad/libwdb/Cakefile,v 9.4 1991-01-03 23:51:49 mike Exp $
 */
#define PRODUCTS	libwdb.ARCH_SUF
#define SRCDIR	libwdb
#define FILES	wdb reg spl ars arbn units pipe
#define	SRCSUFF	.c
#define MANSECTION	3

#include "../Cakefile.defs"

#include "../Cakefile.lib"
#include "../Cakefile.rules"
