/*
 *			fbserv/Cakefile
 *
 *  $Header: /usr/Backup/upgrade/brlcad/brlcad/fbserv/Cakefile,v 11.2 1997-12-03 07:29:23 mike Exp $
 */

#define CONFIGDEFS	RFBD_CONFIG

#define SRCDIR	fbserv
#define PRODUCTS	fbserv
#define	SRCSUFF	.c
#define MANSECTION	1

#define FILES	fbserv

#include "../Cakefile.defs"
#include "../Cakefile.prog"

#define COMPLETE_LIBES	\
	LIBFB LIBBU RFBD_LIBES LIBFB_LIBES LIBBU_LIBES LIBES

/* Explicit composition of each product */

fbserv:	OBJ LIBFB_DEP LIBBU_DEP LIBDM_DEP
	CC LDFLAGS -o fbserv OBJ COMPLETE_LIBES

#include "../Cakefile.rules"



