/*
 *			fbserv/Cakefile
 *
 *  $Header: /usr/Backup/upgrade/brlcad/brlcad/fbserv/Cakefile,v 11.1 1995-01-04 09:53:27 mike Exp $
 */

#define CONFIGDEFS	RFBD_CONFIG

#define SRCDIR	fbserv
#define PRODUCTS	fbserv
#define	SRCSUFF	.c
#define MANSECTION	1

#define FILES	fbserv

#include "../Cakefile.defs"
#include "../Cakefile.prog"

/* Explicit composition of each product */

fbserv:	OBJ LIBFB_DEP
	CC LDFLAGS -o fbserv OBJ LIBFB LIBFB_LIBES RFBD_LIBES LIBES

#include "../Cakefile.rules"
